### ISSUE TITLE
JS file not loading into HTML

### ISSUE THREAD

**Issue by Scotch101Tape** [AtmaWPN/mega-mind#2]
I downloaded the code and open it on both Ms Edge and Chrome. On both the HTML ran but, as you can see on the picture, the js file was never found. It might be a me problem. The path for the js file on my computer is C:\Users\AcerMsft\Downloads\mega-mind-master.zip\mega-mind-master\js\script.js .
![Game - Google Chrome 6_22_2020 9_52_43 AM](https://user-images.githubusercontent.com/66388250/85302046-45e10b00-b46e-11ea-92b5-979419a6e928.png)

**Comment by AtmaWPN** [comment]
Unzip the files
